name: Publish Squirrel Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Build project
      run: dotnet build src/Freshup -c Release
 
    - name: Execute unit tests
      run: dotnet test src/Freshup -c Release --no-build

    - name: Publish project
      run: dotnet publish src/Freshup -c Release --no-build -o Publish
    
    - name: Install Squirrel
      uses: robinraju/release-downloader@v1.7
      with:
        repository: "clowd/Clowd.Squirrel"
        latest: true
        fileName: "SquirrelTools-*.zip"
        out-file-path: "."

    - name: Create Squirrel package
      run: Squirrel.exe pack --packId "Freshup" --framework net6 --packVersion "$env:GITHUB_REF_NAME" --packDirectory Publish

    - name: Archive installer
      uses: actions/upload-artifact@v3
      with:
        name: FreshupSetup
        path: Releases/FreshupSetup.exe